# Utilise une image Node.js légère
FROM node:18-alpine

# Définit le répertoire de travail
WORKDIR /app

# Copie uniquement les fichiers de dépendance
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie tous les fichiers dans l'image
COPY . .

# Expose le port utilisé par Angular
EXPOSE 4200

# Commande pour démarrer en mode développement
CMD ["npm", "start"]
