name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19" # Assurez-vous que c'est la bonne version pour votre projet

      - name: Install dependencies
        run: npm ci # Utiliser npm ci pour une installation plus rapide et reproductible

      - name: Build project
        run: npm run build -- --configuration production

      - name: Deploy to VPS
        run: |
          # Copier les fichiers de build vers le VPS
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p 49999" --rsync-path="sudo rsync" dist/arcadia-zoo-app-front/ ubuntu@${{ secrets.VPS_HOST }}:/var/www/nedellec-julien.fr/html/

          # Vérifier si le fichier index.html est bien présent
          ssh -o StrictHostKeyChecking=no -p 49999 ubuntu@${{ secrets.VPS_HOST }} "ls -l /var/www/nedellec-julien.fr/html/"

          # Démarrer ou redémarrer l'application avec PM2
          ssh -o StrictHostKeyChecking=no -p 49999 ubuntu@${{ secrets.VPS_HOST }} "cd /var/www/nedellec-julien.fr/html/ && pm2 start server.js --name 'arcadia-zoo-app' --watch || pm2 restart 'arcadia-zoo-app'"
