name: Deploy to VPS

on:
  push:
    branches:
      - main # La branche que tu veux déployer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} << 'EOF'
            # Créer le répertoire s'il n'existe pas
            mkdir -p /var/www/arcadia.nedellec-julien.fr
            
            # Aller dans le répertoire
            cd /var/www/arcadia.nedellec-julien.fr
            
            # Initialiser le dépôt Git s'il n'est pas déjà initialisé
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/JulienNedellec/arcadia-zoo-app-front.git
            fi
            
            # Tirer la dernière version du code
            git pull origin main
            
            # Vérifier la présence de docker-compose.yml
            if [ -f "docker-compose.yml" ]; then
              docker-compose down
              docker-compose up -d --build
            else
              echo "Le fichier docker-compose.yml est introuvable !"
              exit 1
            fi
          EOF
