name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19" # Assure-toi que c'est la bonne version pour ton projet

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --configuration production

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} << 'EOF'
            # Se placer dans le répertoire contenant les fichiers Angular
            cd /var/www/vhosts/nedellec-julien.fr/httpdocs/

            # Vérifier si le dossier dist existe et contient les fichiers compilés
            if [ -d dist/arcadia-zoo-app-front ]; then
              echo "Dossier dist/arcadia-zoo-app-front trouvé, copie des fichiers en cours..."
              rsync -avz --delete dist/arcadia-zoo-app-front/* /var/www/vhosts/nedellec-julien.fr/httpdocs/
            else
              echo "Erreur: Le dossier dist/arcadia-zoo-app-front est introuvable."
              exit 1
            fi

            # Optionnel : Redémarrer les conteneurs si Docker Compose est utilisé
            if [ -f docker-compose.yml ]; then
              docker-compose down
              docker-compose up -d --build
            fi
          EOF
