name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19" # Assure-toi que c'est la bonne version pour ton projet

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --configuration production

      - name: Deploy build files to VPS
        run: |
          rsync -avz --delete dist/arcadia-zoo-app-front/* root@${{ secrets.VPS_HOST }}:/var/www/vhosts/nedellec-julien.fr/httpdocs/
